name: restaurant_app
description: POSIMATE BUSINESS APP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'POSIMATE' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  number_to_character: ^0.0.11
#  sunmi_printer: ^1.0.4
  cupertino_icons: ^1.0.5
  oktoast: ^3.1.3+1
  intl: ^0.18.1
  encrypt: ^5.0.1
  modal_progress_hud: ^0.1.3
  badges: ^3.1.1
  esc_pos_printer: ^4.0.3
  esc_pos_utils: ^1.0.0
  path_provider: ^2.0.1
  flutter_dotenv: ^5.1.0
#  flutter_otp: ^0.3.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^2.3.9
  syncfusion_flutter_gauges: ^22.2.7
  autocomplete_textfield: ^2.0.1
  auto_size_text: ^3.0.0
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  share: ^2.0.4
  whatsapp_share: ^2.0.1
#  twilio: ^0.0.1
  file: ^6.1.0
  sqflite: ^2.0.0+3
  file_picker_cross: ^4.3.2
  postgres: ^2.2.0
  printing: ^5.8.0
  fl_chart: ^0.62.0
  font_awesome_flutter: ^10.4.0
  csv: ^5.0.1
  pdf: ^3.7.4
  provider: ^6.0.5

  tuple: any
#  sunmi_printer_plus: ^2.0.13
  geolocator: ^9.0.2
  whatsapp_unilink: ^2.0.0
  get: ^4.6.1


  url_launcher: ^6.0.3
  file_picker: ^4.6.1
  flutter_sunmi_printer: ^0.2.1
#  flutter_html: ^2.1.2
  carousel_pro: ^1.0.0
  esc_pos_bluetooth: any
  http: any
  getwidget: ^3.1.1
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  image_picker: ^0.8.0+3
  async: ^2.6.1
  flutter_svg: any
  flutter_zoom_drawer: ^3.1.1
  print_bluetooth_thermal: ^1.0.5
  esc_pos_utils_plus: ^2.0.1+6
  permission_handler: ^10.4.3
  image: any
  pdf_image_renderer: ^0.7.0
  google_fonts: any
  firebase_crashlytics: ^3.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  fonts:
    - family: CaviarDreams
      fonts:
        - asset: fonts/CaviarDreams.ttf
    - family: FrancoisOne
      fonts:
        - asset: fonts/FrancoisOne-Regular.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf

